#!/usr/bin/env python3
"""Supporting tool for the rfc-writer skill: validate the corpus and keep the
generated INDEX.md honest (charter D-A.2, D-A.3, D-A.6).

  check      validate the collection and fail if INDEX.md differs from what
             `generate` would write — the index is output, like a lockfile
  generate   regenerate INDEX.md from frontmatter
  next       print the next free number, zero-padded
  new        allocate the number, write NNNN-kebab-title.md from the skill's
             template, and regenerate the index

`check` fails on: missing or malformed frontmatter; a leftover prose Status
line; an H1 that disagrees with the frontmatter; a missing decision table; a
row with no grade; a `LOCKED` row with no paths; a duplicate identifier
anywhere in the corpus; a `LOCKED` row of an *accepted* RFC whose paths glob
matches nothing in the repository (draft RFCs may name intended modules,
D-32); a `depends_on`/`informed_by`/`supersedes` id that does not resolve; an
`amended_by` list that disagrees with the `## Amendments` section headings;
and a hand-edited INDEX.md.

Exit codes: 0 ok · 1 usage/IO error · 2 check found problems.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, NoReturn

try:
    import yaml
except ImportError:  # pragma: no cover - torve depends on pyyaml
    sys.exit("error: rfc_index.py needs pyyaml (`pip install pyyaml`)")

STATUSES = ("draft", "accepted", "superseded")
IMPLEMENTATIONS = ("none", "partial", "complete", "abandoned")
GRADES = ("LOCKED", "ASSUMED", "OPEN")
TABLE_HEADER = "| # | Grade | Decision | Paths | Consequence |"
REQUIRED_FIELDS = (
    "id", "title", "status", "depends_on", "informed_by", "supersedes",
    "amended_by", "owner", "description", "schema_version",
)
LIST_FIELDS = ("depends_on", "informed_by", "supersedes", "amended_by")

RFC_FILENAME = re.compile(r"^(\d{4})-([a-z0-9-]+)\.md$")
FRONTMATTER = re.compile(r"\A---\n(.*?\n)---\n", re.S)
H1 = re.compile(r"^# RFC (\d{4}) — (.+)$", re.M)
PROSE_STATUS = re.compile(r"^- \*\*Status:\*\*", re.M)
DECISIONS_HEADING = re.compile(r"^#{2,3}\s*(?:\d+\.\s*)?Decisions\b.*$", re.M | re.I)
AMENDMENT_HEADING = re.compile(r"^### (A-\d+)\b", re.M)
AMENDMENTS_SECTION = re.compile(r"^## Amendments\s*$", re.M)
URI_OR_PROTOCOL_RELATIVE = re.compile(r"^(?:[A-Za-z][A-Za-z0-9+.-]*:|//)")
LOCAL_LINK = re.compile(r"\[[^\]]*\]\((?!#)([^)\s]+)")
TEMPLATE_BLOCK = re.compile(r"```markdown\n(.*?)\n```", re.S)
TEMPLATE_TITLE = "RFC NNNN — <Title>"

GENERATED_NOTE = (
    "<!-- Generated by skills/rfc-writer/scripts/rfc_index.py (charter D-A.6).\n"
    "     Never edit by hand: `rfc_index.py generate` rewrites this file and\n"
    "     `rfc_index.py check` fails CI when it drifts. -->"
)


def fail(message: str) -> NoReturn:
    sys.exit(f"error: {message}")


def find_dir(root: Path) -> Path:
    for name in ("rfcs", "rfc"):
        candidate = root / name
        if candidate.is_dir():
            return candidate
    fail(f"no rfcs/ or rfc/ directory under {root}")


def rfc_files(rfc_dir: Path) -> dict[str, Path]:
    """Zero-padded id -> file. Duplicate numbers are reported by check."""
    found: dict[str, Path] = {}
    for path in sorted(rfc_dir.glob("*.md")):
        match = RFC_FILENAME.match(path.name)
        if match:
            found.setdefault(match.group(1), path)
    return found


def parse_frontmatter(text: str) -> dict[str, Any] | None:
    match = FRONTMATTER.match(text)
    if not match:
        return None
    try:
        loaded = yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None
    if not isinstance(loaded, dict):
        return None
    return {str(k): v for k, v in loaded.items()}


def check_frontmatter(path: Path, fm: dict[str, Any] | None, number: str) -> list[str]:
    if fm is None:
        return [f"{path.name}: no parseable YAML frontmatter (D-A.2)"]
    problems = []
    for field in REQUIRED_FIELDS:
        if field not in fm:
            problems.append(f"{path.name}: frontmatter missing {field!r}")
    if str(fm.get("id", "")) != number:
        problems.append(f"{path.name}: frontmatter id {fm.get('id')!r} != filename {number}")
    status = fm.get("status")
    if status not in STATUSES:
        problems.append(f"{path.name}: status {status!r} is not one of {', '.join(STATUSES)}")
    if status == "superseded" and not fm.get("superseded_by"):
        problems.append(f"{path.name}: superseded without superseded_by")
    implementation = fm.get("implementation")
    if implementation is not None and implementation not in IMPLEMENTATIONS:
        problems.append(
            f"{path.name}: implementation {implementation!r} is not one of "
            f"{', '.join(IMPLEMENTATIONS)} (D-A.11)"
        )
    for field in LIST_FIELDS:
        value = fm.get(field)
        if field in fm and not isinstance(value, list):
            problems.append(f"{path.name}: frontmatter {field} must be a list")
    if not str(fm.get("owner", "")).strip():
        problems.append(f"{path.name}: owner is empty — no one can approve its amendments")
    return problems


def decision_rows(text: str) -> list[tuple[str, str, str, int]] | None:
    """(identifier, grade, paths-cell, header-ok) rows, or None without a table.
    header-ok is carried on the first row as 1/0 so the caller reports it once."""
    heading = DECISIONS_HEADING.search(text)
    if not heading:
        return None
    section = text[heading.end():]
    following = re.search(r"^#{2,3}\s", section, re.M)
    if following:
        section = section[: following.start()]
    rows: list[tuple[str, str, str, int]] = []
    header_ok = 0
    inside = False
    for line in section.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            if inside and stripped:
                break
            continue
        if not inside:
            if stripped.lower().startswith("| #"):
                inside = True
                header_ok = int(stripped == TABLE_HEADER)
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if cells and cells[0] and set(cells[0]) <= set("- :"):
            continue  # the |---| separator
        if len(cells) < 4:
            continue
        rows.append((cells[0].strip("`* "), cells[1].strip("`* "), cells[3], header_ok))
    if not inside:
        return None
    return rows


def paths_globs(cell: str) -> list[str]:
    cleaned = cell.replace("`", " ").strip()
    if not cleaned or set(cleaned) <= set("—- "):
        return []
    return cleaned.split()


def check_decisions(
    path: Path, text: str, status: str, root: Path, seen: dict[str, str]
) -> list[str]:
    found = decision_rows(text)
    if found is None:
        return [f"{path.name}: no Decisions section with a table (D-A.1: the table is what makes it an RFC)"]
    if not found:
        return [f"{path.name}: Decisions section has a header but no rows"]
    problems = []
    if not found[0][3]:
        problems.append(
            f"{path.name}: decision table header is not exactly {TABLE_HEADER!r}"
        )
    for ident, grade, paths_cell, _ in found:
        if ident in seen:
            problems.append(
                f"{path.name}: decision identifier {ident!r} already used in {seen[ident]} — "
                "identifiers are permanent and corpus-unique (D-A.4)"
            )
        else:
            seen[ident] = path.name
        if grade not in GRADES:
            problems.append(
                f"{path.name}: row {ident!r} has grade {grade!r}, not one of {', '.join(GRADES)}"
            )
        globs = paths_globs(paths_cell)
        if grade == "LOCKED":
            if not globs:
                problems.append(
                    f"{path.name}: LOCKED row {ident!r} declares no Paths — "
                    "the silence check skips it and the lock protects nothing"
                )
            elif status == "accepted":
                for pattern in globs:
                    try:
                        matched = next(root.glob(pattern), None)
                    except (ValueError, NotImplementedError):
                        matched = None
                    if matched is None:
                        problems.append(
                            f"{path.name}: LOCKED row {ident!r} paths glob {pattern!r} "
                            "matches nothing in the repository (accepted RFCs cite real areas)"
                        )
    return problems


def check_amendments(path: Path, text: str, fm: dict[str, Any]) -> list[str]:
    declared = [str(a) for a in fm.get("amended_by") or []]
    section = AMENDMENTS_SECTION.search(text)
    present = AMENDMENT_HEADING.findall(text[section.end():]) if section else []
    problems = []
    for a in declared:
        if a not in present:
            problems.append(f"{path.name}: amended_by lists {a} but no '### {a}' heading exists")
    for a in present:
        if a not in declared:
            problems.append(f"{path.name}: amendment section {a} is not listed in amended_by")
    return problems


def check_links(path: Path, text: str, rfc_dir: Path, root: Path) -> list[str]:
    base = root.resolve()
    missing = []
    for match in LOCAL_LINK.finditer(text):
        target = match.group(1).split("#", 1)[0]
        if not target or URI_OR_PROTOCOL_RELATIVE.match(target):
            continue
        for start in (rfc_dir, root):
            try:
                resolved = (start / target).resolve()
            except OSError:
                continue
            if resolved.is_relative_to(base) and resolved.exists():
                break
        else:
            missing.append(
                f"{path.name}: link target {target!r} does not resolve inside the repository"
            )
    return missing


INDEX_TABLE_HEADER = (
    "| # | Title | Status | Impl | Depends on | Amends | One-line routing description |"
)
INDEX_TABLE_SEPARATOR = "| --- | --- | --- | --- | --- | --- | --- |"


def index_row(number: str, path: Path, fm: dict[str, Any]) -> str:
    deps = ", ".join(str(d) for d in fm.get("depends_on") or []) or "—"
    # A list of identifiers, never a summary (A-14): the moment the index
    # describes what an amendment changed, it becomes the stale account.
    amends = ", ".join(str(a) for a in fm.get("amended_by") or []) or "—"
    # An absent value renders as the defined default, never as blank.
    implementation = str(fm.get("implementation") or "none")
    description = " ".join(str(fm.get("description", "")).split())
    return (
        f"| [{number}]({path.name}) | {fm.get('title', '?')} | {fm.get('status', '?')} "
        f"| {implementation} | {deps} | {amends} | {description} |"
    )


def build_index(files: dict[str, Path]) -> str:
    """Everything from the frontmatter, nothing from outside it (D-A.12 as
    reworded by A-14): grouped by kind, with accepted-but-abandoned documents
    separated because that pairing — decisions still inherited, no
    implementation ever coming — is easy to miss as two adjacent cells."""
    design: list[str] = []
    conventions: list[str] = []
    abandoned: list[str] = []
    for number in sorted(files):
        path = files[number]
        fm = parse_frontmatter(path.read_text(encoding="utf-8")) or {}
        row = index_row(number, path, fm)
        if fm.get("status") == "accepted" and fm.get("implementation") == "abandoned":
            abandoned.append(row)
        elif str(fm.get("kind", "")) == "convention":
            conventions.append(row)
        else:
            design.append(row)

    next_free = f"{max((int(n) for n in files), default=0) + 1:04d}"
    lines = [
        "# RFCs",
        "",
        GENERATED_NOTE,
        "",
        "Design corpus for Torve, sorted by the rule in D-A.1: a document with a",
        "table of graded decisions is an RFC and gets a number. The next free",
        f"number is **{next_free}**.",
        "",
    ]
    for heading, rows in (("## Design", design), ("## Conventions", conventions)):
        if rows:
            lines += [heading, "", INDEX_TABLE_HEADER, INDEX_TABLE_SEPARATOR, *rows, ""]
    if abandoned:
        lines += [
            "## Accepted but not implemented",
            "",
            "Decisions from these documents are still inherited. There is no",
            "implementation.",
            "",
            INDEX_TABLE_HEADER,
            INDEX_TABLE_SEPARATOR,
            *abandoned,
            "",
        ]
    lines += [
        "Statuses: draft · accepted · superseded. Impl is the D-A.11 judgement:",
        "none · partial · complete · abandoned.",
        "",
    ]
    return "\n".join(lines)


def cmd_generate(rfc_dir: Path) -> int:
    files = rfc_files(rfc_dir)
    (rfc_dir / "INDEX.md").write_text(build_index(files), encoding="utf-8")
    print(f"generated {rfc_dir / 'INDEX.md'} ({len(files)} RFC(s))")
    return 0


def cmd_check(rfc_dir: Path, root: Path) -> int:
    files = rfc_files(rfc_dir)
    problems: list[str] = []
    warnings: list[str] = []
    seen_numbers: dict[str, list[Path]] = {}
    for path in sorted(rfc_dir.glob("*.md")):
        match = RFC_FILENAME.match(path.name)
        if match:
            seen_numbers.setdefault(match.group(1), []).append(path)
    for number, paths in sorted(seen_numbers.items()):
        if len(paths) > 1:
            problems.append(
                f"RFC {number} is claimed by {len(paths)} files: "
                f"{', '.join(p.name for p in paths)}"
            )

    seen_ids: dict[str, str] = {}
    for number, path in sorted(files.items()):
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        problems += check_frontmatter(path, fm, number)
        if fm is None:
            continue

        h1 = H1.search(text)
        if not h1:
            problems.append(f"{path.name}: no '# RFC NNNN — Title' heading")
        else:
            if h1.group(1) != number:
                problems.append(f"{path.name}: H1 says RFC {h1.group(1)}, filename says {number}")
            if h1.group(2).strip() != str(fm.get("title", "")).strip():
                problems.append(
                    f"{path.name}: H1 title {h1.group(2).strip()!r} != frontmatter "
                    f"title {fm.get('title')!r}"
                )
        if PROSE_STATUS.search(text):
            problems.append(
                f"{path.name}: leftover '- **Status:**' prose line — status lives in frontmatter (D-A.2)"
            )

        for field in ("depends_on", "informed_by", "supersedes"):
            for ref in fm.get(field) or []:
                if str(ref) not in files:
                    problems.append(f"{path.name}: {field} names {ref!r}, no such RFC")

        problems += check_decisions(path, text, str(fm.get("status")), root, seen_ids)
        problems += check_amendments(path, text, fm)
        warnings += check_links(path, text, rfc_dir, root)

    index_path = rfc_dir / "INDEX.md"
    if not index_path.is_file():
        problems.append("INDEX.md is missing — run `rfc_index.py generate`")
    elif index_path.read_text(encoding="utf-8") != build_index(files):
        problems.append(
            "INDEX.md differs from what `generate` writes — it is generated output (D-A.6); "
            "run `rfc_index.py generate` instead of editing it"
        )

    for problem in problems:
        print(f"PROBLEM {problem}")
    for warning in warnings:
        print(f"WARN    {warning}")
    verdict = "FAIL " if problems else "OK   "
    tail = f", {len(warnings)} warning(s)" if warnings else ""
    print(f"{verdict} {len(files)} RFC(s), {len(problems)} problem(s){tail}")
    return 2 if problems else 0


def next_number(rfc_dir: Path) -> int:
    files = rfc_files(rfc_dir)
    return max((int(n) for n in files), default=0) + 1


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    if not slug:
        fail("title produces an empty slug")
    return slug


def cmd_new(rfc_dir: Path, title: str, script_dir: Path, number: int | None) -> int:
    allocated = next_number(rfc_dir) if number is None else number
    if not 1 <= allocated <= 9999:
        fail(f"--number must be between 1 and 9999 (got {allocated})")
    path = rfc_dir / f"{allocated:04d}-{slugify(title)}.md"
    existing = rfc_files(rfc_dir)
    if f"{allocated:04d}" in existing:
        fail(f"RFC {allocated:04d} already exists as {existing[f'{allocated:04d}'].name}")
    template_path = script_dir.parent / "references" / "rfc-template.md"
    if not template_path.is_file():
        fail(f"template not found at {template_path}")
    match = TEMPLATE_BLOCK.search(template_path.read_text(encoding="utf-8"))
    if not match:
        fail(f"no ```markdown skeleton block in {template_path}")
    body = match.group(1)
    if TEMPLATE_TITLE not in body:
        fail(f"references/rfc-template.md lost its {TEMPLATE_TITLE!r} placeholder")
    body = (
        body.replace(TEMPLATE_TITLE, f"RFC {allocated:04d} — {title}")
        .replace('id: "NNNN"', f'id: "{allocated:04d}"')
        .replace("title: <Title>", f"title: {title}")
    )
    try:
        with path.open("x", encoding="utf-8") as handle:
            handle.write(body + "\n")
    except FileExistsError:
        fail(f"{path.name} was created by another process — re-run to take the next number")
    cmd_generate(rfc_dir)
    print(f"created {path}")
    print("next: fill the frontmatter description and the Scope paragraph")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="repo root (default: cwd)")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", type=Path, default=argparse.SUPPRESS, help="repo root")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check", parents=[common])
    sub.add_parser("generate", parents=[common])
    sub.add_parser("next", parents=[common])
    new = sub.add_parser("new", parents=[common])
    new.add_argument("title")
    new.add_argument("--number", type=int, help="use this number instead of the next free one")

    args = parser.parse_args()
    rfc_dir = find_dir(args.root)

    if args.cmd == "check":
        return cmd_check(rfc_dir, args.root)
    if args.cmd == "generate":
        return cmd_generate(rfc_dir)
    if args.cmd == "next":
        print(f"{next_number(rfc_dir):04d}")
        return 0
    return cmd_new(rfc_dir, args.title, Path(__file__).resolve().parent, args.number)


if __name__ == "__main__":
    sys.exit(main())
