"""The RFC format, owned by the package (RFC 0007 §3a, D-7.12): parsing,
corpus validation, and the generated index. Validation depends on no installed
skill — the skill teaches content, this module checks form.

`check_corpus` is the whole check behind `torve rfc check` and the `rfc-valid`
gate. It needs no store and no network (D-7.16): every input is the working
tree. Problems are failures; warnings surface without reddening.

What lives in the corpus directory is bounded (charter D-A.18): only
`NNNN-slug.md` and `INDEX.md`, no subdirectories, and every refusal routes the
offending file somewhere rather than merely rejecting it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast

import yaml

from torve.domain.rfc import GRADES, IMPLEMENTATIONS, KINDS, STATUSES

# ----------------------- #

TABLE_HEADER = "| # | Grade | Decision | Paths | Consequence |"
REQUIRED_FIELDS = (
    "id", "title", "status", "depends_on", "informed_by", "supersedes",
    "amended_by", "owner", "description", "schema_version",
)
LIST_FIELDS = ("depends_on", "informed_by", "supersedes", "amended_by")

RFC_FILENAME = re.compile(r"^(\d{4})-([a-z0-9-]+)\.md$")
NUMBER_ONLY = re.compile(r"^\d{4}(\.md)?$")
FRONTMATTER = re.compile(r"\A---\n(.*?\n)---\n", re.S)
H1 = re.compile(r"^# RFC (\d{4}) — (.+)$", re.M)
PROSE_STATUS = re.compile(r"^- \*\*Status:\*\*", re.M)
DECISIONS_HEADING = re.compile(r"^#{2,3}\s*(?:\d+\.\s*)?Decisions\b.*$", re.M | re.I)
AMENDMENT_HEADING = re.compile(r"^### (A-\d+)\b", re.M)
AMENDMENTS_SECTION = re.compile(r"^## Amendments\s*$", re.M)
URI_OR_PROTOCOL_RELATIVE = re.compile(r"^(?:[A-Za-z][A-Za-z0-9+.-]*:|//)")
LOCAL_LINK = re.compile(r"\[[^\]]*\]\((?!#)([^)\s]+)")
# A cited source location with a line number (0007 §3a "rot"): only paths that
# actually exist in the repository count — an illustrative `file.py:42` in
# prose names nothing and rots nothing.
LINE_CITE = re.compile(r"(?<![\w/])((?:[\w.-]+/)*[\w.-]+\.[A-Za-z0-9_]+):(\d+)")
FENCED_BLOCK = re.compile(r"^```.*?^```[ \t]*$", re.M | re.S)
HEADING = re.compile(r"^(#{2,3})\s+(.+?)\s*$", re.M)
HEADING_NUMBER = re.compile(r"^\d+[a-z]?(\.\d+)*\.?\s+")
# A citation of a dotted decision identifier (charter-decomposition patch §6):
# with one family split across two documents, every citation must resolve to
# exactly one definition somewhere in the corpus. The undotted legacy ids
# (D-27, D-21a) are too short to scan for without false positives.
DECISION_CITE = re.compile(r"\bD-[A-Za-z0-9]+\.\d+[a-z]?\b")

GENERATED_NOTE = (
    "<!-- Generated by `torve rfc index` (charter D-A.6).\n"
    "     Never edit by hand: `torve rfc index` rewrites this file and\n"
    "     `torve rfc check` fails CI when it drifts. -->"
)

# ....................... #


@dataclass
class CheckReport:
    """Everything `check` found: problems redden, warnings surface."""

    count: int = 0
    problems: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


def rfc_files(rfc_dir: Path) -> dict[str, Path]:
    """Zero-padded id -> file. Duplicate numbers are reported by check."""
    found: dict[str, Path] = {}
    for path in sorted(rfc_dir.glob("*.md")):
        match = RFC_FILENAME.match(path.name)
        if match:
            found.setdefault(match.group(1), path)
    return found


def parse_frontmatter(text: str) -> dict[str, Any] | None:
    match = FRONTMATTER.match(text)
    if not match:
        return None
    try:
        loaded = yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None
    if not isinstance(loaded, dict):
        return None
    return {str(k): v for k, v in cast("dict[str, Any]", loaded).items()}


def fm_list(fm: dict[str, Any], fname: str) -> list[str]:
    """A frontmatter list field as strings; anything malformed reads as empty
    (check_frontmatter reports the malformation itself)."""
    value = fm.get(fname)
    if not isinstance(value, list):
        return []
    return [str(item) for item in cast("list[object]", value)]


def next_number(rfc_dir: Path) -> int:
    """The maximum that exists, plus one (D-A.17): derived, never stored.
    Holes below the maximum stay holes — a number that once existed may be
    cited, and reuse silently redirects every citation (D-A.19)."""
    return max((int(n) for n in rfc_files(rfc_dir)), default=0) + 1


def slugify(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


# ....................... #


def check_directory(rfc_dir: Path) -> list[str]:
    """Only `NNNN-slug.md` and `INDEX.md`, no subdirectories (D-A.18). The
    message routes rather than merely refuses — without routing, the file
    lands in the repository root and the mess has moved, not gone."""
    problems: list[str] = []
    for entry in sorted(rfc_dir.iterdir()):
        name = entry.name
        if name.startswith("."):
            continue  # editor and OS droppings are .gitignore's problem
        if entry.is_dir():
            problems.append(
                f"{name}/: no subdirectories in the corpus — a draft is "
                "`status: draft`, not a folder (D-A.18)"
            )
        elif name == "INDEX.md" or RFC_FILENAME.match(name):
            continue
        elif NUMBER_ONLY.match(name):
            problems.append(f"{name}: filename must be NNNN-slug.md (D-A.18)")
        elif name.endswith((".bak", ".orig", ".old", "~")):
            problems.append(f"{name}: delete it — git is the archive (D-A.18)")
        else:
            problems.append(
                f"{name}: not part of the corpus — pages/ if it documents Torve, "
                "ops/ if it is a one-off procedure (D-A.18)"
            )
    return problems


def check_frontmatter(path: Path, fm: dict[str, Any] | None, number: str) -> list[str]:
    if fm is None:
        return [f"{path.name}: no parseable YAML frontmatter (D-A.2)"]
    problems: list[str] = []
    for fname in REQUIRED_FIELDS:
        if fname not in fm:
            problems.append(f"{path.name}: frontmatter missing {fname!r}")
    if str(fm.get("id", "")) != number:
        problems.append(f"{path.name}: frontmatter id {fm.get('id')!r} != filename {number}")
    status = fm.get("status")
    if status not in STATUSES:
        problems.append(f"{path.name}: status {status!r} is not one of {', '.join(STATUSES)}")
    if status == "superseded" and not fm.get("superseded_by"):
        problems.append(f"{path.name}: superseded without superseded_by")
    kind = fm.get("kind")
    if kind is not None and kind not in KINDS:
        problems.append(
            f"{path.name}: kind {kind!r} is not one of {', '.join(KINDS)}"
        )
    implementation = fm.get("implementation")
    if implementation is not None and implementation not in IMPLEMENTATIONS:
        problems.append(
            f"{path.name}: implementation {implementation!r} is not one of "
            f"{', '.join(IMPLEMENTATIONS)} (D-A.11)"
        )
    for fname in LIST_FIELDS:
        value = fm.get(fname)
        if fname in fm and not isinstance(value, list):
            problems.append(f"{path.name}: frontmatter {fname} must be a list")
    if not str(fm.get("owner", "")).strip():
        problems.append(f"{path.name}: owner is empty — no one can approve its amendments")
    return problems


def check_slug(path: Path, fm: dict[str, Any]) -> list[str]:
    """Loose filename-vs-title correspondence (A-15): catches a file whose
    slug belongs to a different document without demanding one exact
    slugification anyone would have to guess. A warning, not a problem."""
    match = RFC_FILENAME.match(path.name)
    title = str(fm.get("title", ""))
    if not match or not title:
        return []
    slug_words = {w for w in match.group(2).split("-") if len(w) >= 4}
    title_words = {w for w in slugify(title).split("-") if len(w) >= 4}
    if slug_words and title_words and not slug_words & title_words:
        return [
            (f"{path.name}: filename slug shares no word with title {title!r} — "
            "a materially different title is usually a new document (D-A.20)")
        ]
    return []


def decision_rows(text: str) -> list[tuple[str, str, str, int]] | None:
    """(identifier, grade, paths-cell, header-ok) rows, or None without a table.
    header-ok is carried on the first row as 1/0 so the caller reports it once."""
    heading = DECISIONS_HEADING.search(text)
    if not heading:
        return None
    section = text[heading.end():]
    following = re.search(r"^#{2,3}\s", section, re.M)
    if following:
        section = section[: following.start()]
    rows: list[tuple[str, str, str, int]] = []
    header_ok = 0
    inside = False
    for line in section.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            if inside and stripped:
                break
            continue
        if not inside:
            if stripped.lower().startswith("| #"):
                inside = True
                header_ok = int(stripped == TABLE_HEADER)
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if cells and cells[0] and set(cells[0]) <= set("- :"):
            continue  # the |---| separator
        if len(cells) < 4:
            continue
        rows.append((cells[0].strip("`* "), cells[1].strip("`* "), cells[3], header_ok))
    if not inside:
        return None
    return rows


def paths_globs(cell: str) -> list[str]:
    cleaned = cell.replace("`", " ").strip()
    if not cleaned or set(cleaned) <= set("—- "):
        return []
    return cleaned.split()


def check_decisions(
    path: Path, text: str, fm: dict[str, Any], root: Path, seen: dict[str, str]
) -> list[str]:
    # D-32: for RFCs not yet built the globs name the intended module and are
    # refined when it exists. "Not yet built" is `implementation: none` — an
    # accepted document awaiting execution may cite modules that do not exist,
    # while partial or complete implementation means the cited areas are real.
    check_globs = (
        fm.get("status") == "accepted" and (fm.get("implementation") or "none") != "none"
    )
    found = decision_rows(text)
    if found is None:
        return [
            (f"{path.name}: no Decisions section with a table "
            "(D-A.1: the table is what makes it an RFC)")
        ]
    if not found:
        return [f"{path.name}: Decisions section has a header but no rows"]
    problems: list[str] = []
    if not found[0][3]:
        problems.append(f"{path.name}: decision table header is not exactly {TABLE_HEADER!r}")
    for ident, grade, paths_cell, _ in found:
        if ident in seen:
            problems.append(
                f"{path.name}: decision identifier {ident!r} already used in {seen[ident]} — "
                "identifiers are permanent and corpus-unique (D-A.4)"
            )
        else:
            seen[ident] = path.name
        if grade not in GRADES:
            problems.append(
                f"{path.name}: row {ident!r} has grade {grade!r}, not one of {', '.join(GRADES)}"
            )
        globs = paths_globs(paths_cell)
        if grade == "LOCKED":
            if not globs:
                problems.append(
                    f"{path.name}: LOCKED row {ident!r} declares no Paths — "
                    "the silence check skips it and the lock protects nothing"
                )
            elif check_globs:
                for pattern in globs:
                    try:
                        matched = next(root.glob(pattern), None)
                    except (ValueError, NotImplementedError):
                        matched = None
                    if matched is None:
                        problems.append(
                            f"{path.name}: LOCKED row {ident!r} paths glob {pattern!r} "
                            "matches nothing in the repository (an implemented "
                            "RFC cites real areas, D-32)"
                        )
    return problems


def check_amendments(path: Path, text: str, fm: dict[str, Any]) -> list[str]:
    declared = fm_list(fm, "amended_by")
    section = AMENDMENTS_SECTION.search(text)
    present = AMENDMENT_HEADING.findall(text[section.end():]) if section else []
    problems: list[str] = []
    for a in declared:
        if a not in present:
            problems.append(f"{path.name}: amended_by lists {a} but no '### {a}' heading exists")
    for a in present:
        if a not in declared:
            problems.append(f"{path.name}: amendment section {a} is not listed in amended_by")
    return problems


def check_links(path: Path, text: str, rfc_dir: Path, root: Path) -> list[str]:
    base = root.resolve()
    missing: list[str] = []
    for match in LOCAL_LINK.finditer(text):
        target = match.group(1).split("#", 1)[0]
        if not target or URI_OR_PROTOCOL_RELATIVE.match(target):
            continue
        for start in (rfc_dir, root):
            try:
                resolved = (start / target).resolve()
            except OSError:
                continue
            if resolved.is_relative_to(base) and resolved.exists():
                break
        else:
            missing.append(
                f"{path.name}: link target {target!r} does not resolve inside the repository"
            )
    return missing


def check_line_cites(path: Path, text: str, root: Path) -> list[str]:
    """0007 §3a rot: a source path cited with a line number is stale at the
    first refactor above it. Only paths that exist in the repository count —
    an illustrative location in prose names nothing real."""
    body = FRONTMATTER.sub("", text, count=1)
    problems: list[str] = []
    for match in LINE_CITE.finditer(body):
        cited = match.group(1)
        if (root / cited).is_file():
            problems.append(
                f"{path.name}: cites {cited}:{match.group(2)} — line numbers rot "
                "at the first refactor above them (0007 §3a); cite the path alone"
            )
    return problems


def strip_fences(text: str) -> str:
    """Fenced code blocks host examples, not structure: a `#` line or a
    decision id inside one is illustration, never a heading or a citation."""
    return FENCED_BLOCK.sub("", text)


def check_headings(path: Path, text: str) -> list[str]:
    """Two identically-named sections in one document (charter-decomposition
    patch §3): section numbers are stripped before comparing, so a numbered
    prose section duplicating an unnumbered container is caught too."""
    seen: dict[tuple[str, str], str] = {}
    problems: list[str] = []
    for match in HEADING.finditer(strip_fences(text)):
        level, raw = match.group(1), match.group(2)
        normalized = HEADING_NUMBER.sub("", raw).strip().lower()
        if not normalized:
            continue
        key = (level, normalized)
        if key in seen:
            problems.append(
                f"{path.name}: headings {seen[key]!r} and {raw!r} name the same "
                "section twice — one of them is in the wrong document or the wrong form"
            )
        else:
            seen[key] = raw
    return problems


def check_citations(path: Path, text: str, defined: set[str]) -> list[str]:
    """Every dotted `D-*` citation resolves to a definition somewhere in the
    corpus — what keeps a decision family split across documents (A-17) a
    cosmetic wart rather than a real problem. Uniqueness of definitions is
    D-A.4's check; this is the other direction. A warning, not a problem: a
    retired identifier's tombstone (0005's D-5.5 note) legitimately cites an
    id no table defines — see T-0017's log for the promotion condition."""
    warnings: list[str] = []
    reported: set[str] = set()
    for match in DECISION_CITE.finditer(strip_fences(text)):
        cited = match.group(0)
        if cited not in defined and cited not in reported:
            reported.add(cited)
            warnings.append(
                f"{path.name}: cites {cited}, which no decision table in the "
                "corpus defines"
            )
    return warnings


def defined_identifiers(files: dict[str, Path]) -> set[str]:
    """Every decision identifier defined anywhere in the corpus."""
    defined: set[str] = set()
    for path in files.values():
        for ident, _grade, _paths, _header in decision_rows(
            path.read_text(encoding="utf-8")
        ) or []:
            defined.add(ident)
    return defined


def check_graph(
    files: dict[str, Path], frontmatter: dict[str, dict[str, Any]]
) -> tuple[list[str], list[str]]:
    """Cycles in `depends_on` are problems; an accepted document depending on
    one that is not accepted is surfaced as a warning (D-A.10 — the hard
    refusal lives in `torve plan`, and one known violation, 0009 -> 0004,
    awaits resolution before this can redden the corpus)."""
    edges = {
        number: [d for d in fm_list(fm, "depends_on") if d in files]
        for number, fm in frontmatter.items()
    }
    problems: list[str] = []
    warnings: list[str] = []

    seen_cycles: set[frozenset[str]] = set()
    state: dict[str, int] = {}  # 1 = on the current path, 2 = done

    def visit(number: str, trail: list[str]) -> None:
        state[number] = 1
        for target in edges.get(number, []):
            if state.get(target) == 1:
                cycle = [*trail[trail.index(target):], target]
                key = frozenset(cycle)
                if key not in seen_cycles:
                    seen_cycles.add(key)
                    problems.append(
                        "depends_on cycle: " + " -> ".join(cycle)
                        + " — the graph must be acyclic (0007 §3a)"
                    )
            elif state.get(target) != 2:
                visit(target, [*trail, target])
        state[number] = 2

    for number in sorted(edges):
        if state.get(number) != 2:
            visit(number, [number])

    for number, fm in sorted(frontmatter.items()):
        if fm.get("status") != "accepted":
            continue
        for target in edges.get(number, []):
            target_status = str(frontmatter.get(target, {}).get("status", "?"))
            if target_status != "accepted":
                warnings.append(
                    f"{files[number].name}: accepted but depends_on {target} which is "
                    f"{target_status} — no inheritance from a non-accepted document (D-A.10)"
                )
    return problems, warnings


# ....................... #

INDEX_TABLE_HEADER = (
    "| # | Title | Status | Impl | Depends on | Amends | One-line routing description |"
)
INDEX_TABLE_SEPARATOR = "| --- | --- | --- | --- | --- | --- | --- |"


def index_row(number: str, path: Path, fm: dict[str, Any]) -> str:
    deps = ", ".join(fm_list(fm, "depends_on")) or "—"
    # A list of identifiers, never a summary (A-14): the moment the index
    # describes what an amendment changed, it becomes the stale account.
    amends = ", ".join(fm_list(fm, "amended_by")) or "—"
    # An absent value renders as the defined default, never as blank.
    implementation = str(fm.get("implementation") or "none")
    description = " ".join(str(fm.get("description", "")).split())
    return (
        f"| [{number}]({path.name}) | {fm.get('title', '?')} | {fm.get('status', '?')} "
        f"| {implementation} | {deps} | {amends} | {description} |"
    )


def build_index(files: dict[str, Path]) -> str:
    """Everything from the frontmatter, nothing from outside it (D-A.12 as
    reworded by A-14): grouped by kind, with accepted-but-abandoned documents
    separated because that pairing — decisions still inherited, no
    implementation ever coming — is easy to miss as two adjacent cells."""
    design: list[str] = []
    conventions: list[str] = []
    abandoned: list[str] = []
    for number in sorted(files):
        path = files[number]
        fm = parse_frontmatter(path.read_text(encoding="utf-8")) or {}
        row = index_row(number, path, fm)
        if fm.get("status") == "accepted" and fm.get("implementation") == "abandoned":
            abandoned.append(row)
        elif str(fm.get("kind", "")) == "convention":
            conventions.append(row)
        else:
            design.append(row)

    next_free = f"{max((int(n) for n in files), default=0) + 1:04d}"
    lines = [
        "# RFCs",
        "",
        GENERATED_NOTE,
        "",
        "Design corpus for Torve, sorted by the rule in D-A.1: a document with a",
        "table of graded decisions is an RFC and gets a number. The next free",
        f"number is **{next_free}**.",
        "",
    ]
    for heading, rows in (("## Design", design), ("## Conventions", conventions)):
        if rows:
            lines += [heading, "", INDEX_TABLE_HEADER, INDEX_TABLE_SEPARATOR, *rows, ""]
    if abandoned:
        lines += [
            "## Accepted but not implemented",
            "",
            "Decisions from these documents are still inherited. There is no",
            "implementation.",
            "",
            INDEX_TABLE_HEADER,
            INDEX_TABLE_SEPARATOR,
            *abandoned,
            "",
        ]
    lines += [
        "Statuses: draft · accepted · superseded. Impl is the D-A.11 judgement:",
        "none · partial · complete · abandoned.",
        "",
    ]
    return "\n".join(lines)


# ....................... #


def check_corpus(rfc_dir: Path, root: Path) -> CheckReport:
    """The whole of `torve rfc check` over one corpus directory."""
    report = CheckReport()
    report.problems += check_directory(rfc_dir)

    seen_numbers: dict[str, list[Path]] = {}
    for path in sorted(rfc_dir.glob("*.md")):
        match = RFC_FILENAME.match(path.name)
        if match:
            seen_numbers.setdefault(match.group(1), []).append(path)
    for number, paths in sorted(seen_numbers.items()):
        if len(paths) > 1:
            report.problems.append(
                f"RFC {number} is claimed by {len(paths)} files: "
                f"{', '.join(p.name for p in paths)}"
            )

    files = rfc_files(rfc_dir)
    report.count = len(files)
    defined = defined_identifiers(files)
    frontmatter: dict[str, dict[str, Any]] = {}
    seen_ids: dict[str, str] = {}
    for number, path in sorted(files.items()):
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        report.problems += check_frontmatter(path, fm, number)
        if fm is None:
            continue
        frontmatter[number] = fm

        h1 = H1.search(text)
        if not h1:
            report.problems.append(f"{path.name}: no '# RFC NNNN — Title' heading")
        else:
            if h1.group(1) != number:
                report.problems.append(
                    f"{path.name}: H1 says RFC {h1.group(1)}, filename says {number}"
                )
            if h1.group(2).strip() != str(fm.get("title", "")).strip():
                report.problems.append(
                    f"{path.name}: H1 title {h1.group(2).strip()!r} != frontmatter "
                    f"title {fm.get('title')!r}"
                )
        if PROSE_STATUS.search(text):
            report.problems.append(
                f"{path.name}: leftover '- **Status:**' prose line — "
                "status lives in frontmatter (D-A.2)"
            )

        for fname in ("depends_on", "informed_by", "supersedes"):
            for ref in fm_list(fm, fname):
                if ref not in files:
                    report.problems.append(f"{path.name}: {fname} names {ref!r}, no such RFC")

        report.problems += check_decisions(path, text, fm, root, seen_ids)
        report.problems += check_amendments(path, text, fm)
        report.problems += check_line_cites(path, text, root)
        report.problems += check_headings(path, text)
        report.warnings += check_citations(path, text, defined)
        report.warnings += check_slug(path, fm)
        report.warnings += check_links(path, text, rfc_dir, root)

    graph_problems, graph_warnings = check_graph(files, frontmatter)
    report.problems += graph_problems
    report.warnings += graph_warnings

    index_path = rfc_dir / "INDEX.md"
    if not index_path.is_file():
        report.problems.append("INDEX.md is missing — run `torve rfc index`")
    elif index_path.read_text(encoding="utf-8") != build_index(files):
        report.problems.append(
            "INDEX.md differs from what `torve rfc index` writes — it is generated "
            "output (D-A.6); regenerate it instead of editing it"
        )
    return report
